service: streaming-bms

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1
  memorySize: 192

functions:
  getBMStickets:
    handler: handler.getBMStickets

    events:
      - schedule: 
        rate: rate(15 minutes)
        enabled: true

    # environment: ${file(env.yml)}
